# Generated by Django 3.2.6 on 2021-11-26 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Postfrom',
            new_name='Postform',
        ),
    ]
